### ISSUE TITLE
Chrope dark mode flag

### ISSUE THREAD

**Issue by TheCarpetMerchant** [fraoustin/redmine_dark#2]
Hey, just so you know, this doesn't work with the Chrome dark mode flag.

**Comment by fraoustin** [comment]
for me it's ok on chrome ... why doesn't work?

**Comment by TheCarpetMerchant** [comment]
Have you enabled the dark mode flag ?

**Comment by fraoustin** [comment]
Yes and after I clcik on link "dark mode" on redmine

**Comment by fraoustin** [comment]
You want a flag automatic (based on dark mode of chrome) ?

**Comment by fraoustin** [comment]
Hi i add the dark mode mode flag from chrome ou firefox
new version 1.0.2
